#!/usr/bin/env sh

# time

seconds2hms() {
  local h=$(($1 / 3600))
  local m=$((($1 / 60) % 60))
  local s=$(($1 % 60))
  printf '%d:%02d:%02d\n' $h $m $s
}

stopwatch() {
  # call me twice.
  # Useful sometimes instead of time cmd or time builtin
  if [ $# -eq 0 ]; then
    error "Expected 1 arg. Usage: $0 'start | stop'"
    return 1
  fi
  if [ $1 = 'start' ]; then
    start_time=$(date '+%s')
    return 0
  elif [ $1 = 'stop' ]; then
    end_time=$(date '+%s')
    seconds2hms $((end_time - start_time))
  else
    warning "bad function argument"
    return 1
  fi
}
